package com.m11n.hermes.core.model;

import java.util.List;

import javax.xml.bind.annotation.XmlRootElement;

import org.joda.beans.BeanDefinition;
import org.joda.beans.MetaBean;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectBean;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.util.Map;
import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

@BeanDefinition
@JsonIgnoreProperties({"meta", "metaBean"})
@XmlRootElement(name = "create_documents_request")
public class CreateDocumentsRequest extends DirectBean {

    @PropertyDefinition
    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    private List<String> OrderIds;

    //------------------------- AUTOGENERATED START -------------------------
    ///CLOVER:OFF
    /**
     * The meta-bean for {@code CreateDocumentsRequest}.
     * @return the meta-bean, not null
     */
    public static CreateDocumentsRequest.Meta meta() {
        return CreateDocumentsRequest.Meta.INSTANCE;
    }

    static {
        JodaBeanUtils.registerMetaBean(CreateDocumentsRequest.Meta.INSTANCE);
    }

    @Override
    public CreateDocumentsRequest.Meta metaBean() {
        return CreateDocumentsRequest.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the OrderIds.
     * @return the value of the property
     */
    public List<String> getOrderIds() {
        return OrderIds;
    }

    /**
     * Sets the OrderIds.
     * @param OrderIds  the new value of the property
     */
    public void setOrderIds(List<String> OrderIds) {
        this.OrderIds = OrderIds;
    }

    /**
     * Gets the the {@code OrderIds} property.
     * @return the property, not null
     */
    public final Property<List<String>> OrderIds() {
        return metaBean().OrderIds().createProperty(this);
    }

    //-----------------------------------------------------------------------
    @Override
    public CreateDocumentsRequest clone() {
        return JodaBeanUtils.cloneAlways(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            CreateDocumentsRequest other = (CreateDocumentsRequest) obj;
            return JodaBeanUtils.equal(getOrderIds(), other.getOrderIds());
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash = hash * 31 + JodaBeanUtils.hashCode(getOrderIds());
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(64);
        buf.append("CreateDocumentsRequest{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    protected void toString(StringBuilder buf) {
        buf.append("OrderIds").append('=').append(JodaBeanUtils.toString(getOrderIds())).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code CreateDocumentsRequest}.
     */
    public static class Meta extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code OrderIds} property.
         */
        @SuppressWarnings({"unchecked", "rawtypes" })
        private final MetaProperty<List<String>> OrderIds = DirectMetaProperty.ofReadWrite(
                this, "OrderIds", CreateDocumentsRequest.class, (Class) List.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null,
                "OrderIds");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case 1298927786:  // OrderIds
                    return OrderIds;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public BeanBuilder<? extends CreateDocumentsRequest> builder() {
            return new DirectBeanBuilder<CreateDocumentsRequest>(new CreateDocumentsRequest());
        }

        @Override
        public Class<? extends CreateDocumentsRequest> beanType() {
            return CreateDocumentsRequest.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code OrderIds} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<List<String>> OrderIds() {
            return OrderIds;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 1298927786:  // OrderIds
                    return ((CreateDocumentsRequest) bean).getOrderIds();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @SuppressWarnings("unchecked")
        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 1298927786:  // OrderIds
                    ((CreateDocumentsRequest) bean).setOrderIds((List<String>) newValue);
                    return;
            }
            super.propertySet(bean, propertyName, newValue, quiet);
        }

    }

    ///CLOVER:ON
    //-------------------------- AUTOGENERATED END --------------------------
}
