package com.m11n.hermes.core.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

import org.joda.beans.BeanDefinition;
import org.joda.beans.MetaBean;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectBean;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.util.Map;
import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

@BeanDefinition
@JsonIgnoreProperties({"meta", "metaBean"})
@XmlRootElement(name = "documents_printjob_item")
@Entity
@Table(name = "hermes_documents_printjob_item")
public class DocumentsPrintjobItem extends DirectBean {

    @PropertyDefinition
    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @Id
    @Column(name = "id", unique = true)
    private Integer id;

    @PropertyDefinition
    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @Column(name = "printjob_id")
    private Integer printjobId;

    @PropertyDefinition
    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @Column(name = "document_id")
    private Integer documentId;

    @PropertyDefinition
    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @Column(name = "status")
    private String status;

    @PropertyDefinition
    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @Column(name = "sequence")
    private Integer sequence;

    @PropertyDefinition
    @JsonSerialize
    @Column(name = "printed_at")
    private Date printedAt = new Date();

    //------------------------- AUTOGENERATED START -------------------------
    ///CLOVER:OFF
    /**
     * The meta-bean for {@code DocumentsPrintjobItem}.
     * @return the meta-bean, not null
     */
    public static DocumentsPrintjobItem.Meta meta() {
        return DocumentsPrintjobItem.Meta.INSTANCE;
    }

    static {
        JodaBeanUtils.registerMetaBean(DocumentsPrintjobItem.Meta.INSTANCE);
    }

    @Override
    public DocumentsPrintjobItem.Meta metaBean() {
        return DocumentsPrintjobItem.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the id.
     * @return the value of the property
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the id.
     * @param id  the new value of the property
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Gets the the {@code id} property.
     * @return the property, not null
     */
    public final Property<Integer> id() {
        return metaBean().id().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the printjobId.
     * @return the value of the property
     */
    public Integer getPrintjobId() {
        return printjobId;
    }

    /**
     * Sets the printjobId.
     * @param printjobId  the new value of the property
     */
    public void setPrintjobId(Integer printjobId) {
        this.printjobId = printjobId;
    }

    /**
     * Gets the the {@code printjobId} property.
     * @return the property, not null
     */
    public final Property<Integer> printjobId() {
        return metaBean().printjobId().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the documentId.
     * @return the value of the property
     */
    public Integer getDocumentId() {
        return documentId;
    }

    /**
     * Sets the documentId.
     * @param documentId  the new value of the property
     */
    public void setDocumentId(Integer documentId) {
        this.documentId = documentId;
    }

    /**
     * Gets the the {@code documentId} property.
     * @return the property, not null
     */
    public final Property<Integer> documentId() {
        return metaBean().documentId().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the status.
     * @return the value of the property
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the status.
     * @param status  the new value of the property
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Gets the the {@code status} property.
     * @return the property, not null
     */
    public final Property<String> status() {
        return metaBean().status().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the sequence.
     * @return the value of the property
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * Sets the sequence.
     * @param sequence  the new value of the property
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * Gets the the {@code sequence} property.
     * @return the property, not null
     */
    public final Property<Integer> sequence() {
        return metaBean().sequence().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the printedAt.
     * @return the value of the property
     */
    public Date getPrintedAt() {
        return printedAt;
    }

    /**
     * Sets the printedAt.
     * @param printedAt  the new value of the property
     */
    public void setPrintedAt(Date printedAt) {
        this.printedAt = printedAt;
    }

    /**
     * Gets the the {@code printedAt} property.
     * @return the property, not null
     */
    public final Property<Date> printedAt() {
        return metaBean().printedAt().createProperty(this);
    }

    //-----------------------------------------------------------------------
    @Override
    public DocumentsPrintjobItem clone() {
        return JodaBeanUtils.cloneAlways(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            DocumentsPrintjobItem other = (DocumentsPrintjobItem) obj;
            return JodaBeanUtils.equal(getId(), other.getId()) &&
                    JodaBeanUtils.equal(getPrintjobId(), other.getPrintjobId()) &&
                    JodaBeanUtils.equal(getDocumentId(), other.getDocumentId()) &&
                    JodaBeanUtils.equal(getStatus(), other.getStatus()) &&
                    JodaBeanUtils.equal(getSequence(), other.getSequence()) &&
                    JodaBeanUtils.equal(getPrintedAt(), other.getPrintedAt());
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash = hash * 31 + JodaBeanUtils.hashCode(getId());
        hash = hash * 31 + JodaBeanUtils.hashCode(getPrintjobId());
        hash = hash * 31 + JodaBeanUtils.hashCode(getDocumentId());
        hash = hash * 31 + JodaBeanUtils.hashCode(getStatus());
        hash = hash * 31 + JodaBeanUtils.hashCode(getSequence());
        hash = hash * 31 + JodaBeanUtils.hashCode(getPrintedAt());
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(224);
        buf.append("DocumentsPrintjobItem{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    protected void toString(StringBuilder buf) {
        buf.append("id").append('=').append(JodaBeanUtils.toString(getId())).append(',').append(' ');
        buf.append("printjobId").append('=').append(JodaBeanUtils.toString(getPrintjobId())).append(',').append(' ');
        buf.append("documentId").append('=').append(JodaBeanUtils.toString(getDocumentId())).append(',').append(' ');
        buf.append("status").append('=').append(JodaBeanUtils.toString(getStatus())).append(',').append(' ');
        buf.append("sequence").append('=').append(JodaBeanUtils.toString(getSequence())).append(',').append(' ');
        buf.append("printedAt").append('=').append(JodaBeanUtils.toString(getPrintedAt())).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code DocumentsPrintjobItem}.
     */
    public static class Meta extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code id} property.
         */
        private final MetaProperty<Integer> id = DirectMetaProperty.ofReadWrite(
                this, "id", DocumentsPrintjobItem.class, Integer.class);
        /**
         * The meta-property for the {@code printjobId} property.
         */
        private final MetaProperty<Integer> printjobId = DirectMetaProperty.ofReadWrite(
                this, "printjobId", DocumentsPrintjobItem.class, Integer.class);
        /**
         * The meta-property for the {@code documentId} property.
         */
        private final MetaProperty<Integer> documentId = DirectMetaProperty.ofReadWrite(
                this, "documentId", DocumentsPrintjobItem.class, Integer.class);
        /**
         * The meta-property for the {@code status} property.
         */
        private final MetaProperty<String> status = DirectMetaProperty.ofReadWrite(
                this, "status", DocumentsPrintjobItem.class, String.class);
        /**
         * The meta-property for the {@code sequence} property.
         */
        private final MetaProperty<Integer> sequence = DirectMetaProperty.ofReadWrite(
                this, "sequence", DocumentsPrintjobItem.class, Integer.class);
        /**
         * The meta-property for the {@code printedAt} property.
         */
        private final MetaProperty<Date> printedAt = DirectMetaProperty.ofReadWrite(
                this, "printedAt", DocumentsPrintjobItem.class, Date.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null,
                "id",
                "printjobId",
                "documentId",
                "status",
                "sequence",
                "printedAt");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case 3355:  // id
                    return id;
                case 148871979:  // printjobId
                    return printjobId;
                case -814940266:  // documentId
                    return documentId;
                case -892481550:  // status
                    return status;
                case 1349547969:  // sequence
                    return sequence;
                case -1796473505:  // printedAt
                    return printedAt;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public BeanBuilder<? extends DocumentsPrintjobItem> builder() {
            return new DirectBeanBuilder<DocumentsPrintjobItem>(new DocumentsPrintjobItem());
        }

        @Override
        public Class<? extends DocumentsPrintjobItem> beanType() {
            return DocumentsPrintjobItem.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code id} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<Integer> id() {
            return id;
        }

        /**
         * The meta-property for the {@code printjobId} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<Integer> printjobId() {
            return printjobId;
        }

        /**
         * The meta-property for the {@code documentId} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<Integer> documentId() {
            return documentId;
        }

        /**
         * The meta-property for the {@code status} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> status() {
            return status;
        }

        /**
         * The meta-property for the {@code sequence} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<Integer> sequence() {
            return sequence;
        }

        /**
         * The meta-property for the {@code printedAt} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<Date> printedAt() {
            return printedAt;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 3355:  // id
                    return ((DocumentsPrintjobItem) bean).getId();
                case 148871979:  // printjobId
                    return ((DocumentsPrintjobItem) bean).getPrintjobId();
                case -814940266:  // documentId
                    return ((DocumentsPrintjobItem) bean).getDocumentId();
                case -892481550:  // status
                    return ((DocumentsPrintjobItem) bean).getStatus();
                case 1349547969:  // sequence
                    return ((DocumentsPrintjobItem) bean).getSequence();
                case -1796473505:  // printedAt
                    return ((DocumentsPrintjobItem) bean).getPrintedAt();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 3355:  // id
                    ((DocumentsPrintjobItem) bean).setId((Integer) newValue);
                    return;
                case 148871979:  // printjobId
                    ((DocumentsPrintjobItem) bean).setPrintjobId((Integer) newValue);
                    return;
                case -814940266:  // documentId
                    ((DocumentsPrintjobItem) bean).setDocumentId((Integer) newValue);
                    return;
                case -892481550:  // status
                    ((DocumentsPrintjobItem) bean).setStatus((String) newValue);
                    return;
                case 1349547969:  // sequence
                    ((DocumentsPrintjobItem) bean).setSequence((Integer) newValue);
                    return;
                case -1796473505:  // printedAt
                    ((DocumentsPrintjobItem) bean).setPrintedAt((Date) newValue);
                    return;
            }
            super.propertySet(bean, propertyName, newValue, quiet);
        }

    }

    ///CLOVER:ON
    //-------------------------- AUTOGENERATED END --------------------------
}
