package com.m11n.hermes.core.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import org.joda.beans.*;
import org.joda.beans.impl.direct.*;
import org.springframework.data.annotation.Id;

import javax.xml.bind.annotation.XmlRootElement;
import java.util.Date;
import java.util.Map;
import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.BeanDefinition;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectBean;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

@BeanDefinition
@JsonIgnoreProperties({"meta", "metaBean"})
@XmlRootElement(name = "log")
public class Log extends DirectBean
{
    @PropertyDefinition
    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @Id
    private String uid;

    @PropertyDefinition
    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    private String charge;

    @PropertyDefinition
    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    private String orderId;

    @PropertyDefinition
    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    private String unitId;

    @PropertyDefinition
    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    private String invoiceId;

    @PropertyDefinition
    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    private String shippingId;

    @PropertyDefinition
    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    private Date processedAt;

    @PropertyDefinition
    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    private String productType;
    //------------------------- AUTOGENERATED START -------------------------
    ///CLOVER:OFF
    /**
     * The meta-bean for {@code Log}.
     * @return the meta-bean, not null
     */
    public static Log.Meta meta() {
        return Log.Meta.INSTANCE;
    }

    static {
        JodaBeanUtils.registerMetaBean(Log.Meta.INSTANCE);
    }

    @Override
    public Log.Meta metaBean() {
        return Log.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the uid.
     * @return the value of the property
     */
    public String getUid() {
        return uid;
    }

    /**
     * Sets the uid.
     * @param uid  the new value of the property
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * Gets the the {@code uid} property.
     * @return the property, not null
     */
    public final Property<String> uid() {
        return metaBean().uid().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the charge.
     * @return the value of the property
     */
    public String getCharge() {
        return charge;
    }

    /**
     * Sets the charge.
     * @param charge  the new value of the property
     */
    public void setCharge(String charge) {
        this.charge = charge;
    }

    /**
     * Gets the the {@code charge} property.
     * @return the property, not null
     */
    public final Property<String> charge() {
        return metaBean().charge().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the orderId.
     * @return the value of the property
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * Sets the orderId.
     * @param orderId  the new value of the property
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * Gets the the {@code orderId} property.
     * @return the property, not null
     */
    public final Property<String> orderId() {
        return metaBean().orderId().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the unitId.
     * @return the value of the property
     */
    public String getUnitId() {
        return unitId;
    }

    /**
     * Sets the unitId.
     * @param unitId  the new value of the property
     */
    public void setUnitId(String unitId) {
        this.unitId = unitId;
    }

    /**
     * Gets the the {@code unitId} property.
     * @return the property, not null
     */
    public final Property<String> unitId() {
        return metaBean().unitId().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the invoiceId.
     * @return the value of the property
     */
    public String getInvoiceId() {
        return invoiceId;
    }

    /**
     * Sets the invoiceId.
     * @param invoiceId  the new value of the property
     */
    public void setInvoiceId(String invoiceId) {
        this.invoiceId = invoiceId;
    }

    /**
     * Gets the the {@code invoiceId} property.
     * @return the property, not null
     */
    public final Property<String> invoiceId() {
        return metaBean().invoiceId().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the shippingId.
     * @return the value of the property
     */
    public String getShippingId() {
        return shippingId;
    }

    /**
     * Sets the shippingId.
     * @param shippingId  the new value of the property
     */
    public void setShippingId(String shippingId) {
        this.shippingId = shippingId;
    }

    /**
     * Gets the the {@code shippingId} property.
     * @return the property, not null
     */
    public final Property<String> shippingId() {
        return metaBean().shippingId().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the processedAt.
     * @return the value of the property
     */
    public Date getProcessedAt() {
        return processedAt;
    }

    /**
     * Sets the processedAt.
     * @param processedAt  the new value of the property
     */
    public void setProcessedAt(Date processedAt) {
        this.processedAt = processedAt;
    }

    /**
     * Gets the the {@code processedAt} property.
     * @return the property, not null
     */
    public final Property<Date> processedAt() {
        return metaBean().processedAt().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the productType.
     * @return the value of the property
     */
    public String getProductType() {
        return productType;
    }

    /**
     * Sets the productType.
     * @param productType  the new value of the property
     */
    public void setProductType(String productType) {
        this.productType = productType;
    }

    /**
     * Gets the the {@code productType} property.
     * @return the property, not null
     */
    public final Property<String> productType() {
        return metaBean().productType().createProperty(this);
    }

    //-----------------------------------------------------------------------
    @Override
    public Log clone() {
        return JodaBeanUtils.cloneAlways(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            Log other = (Log) obj;
            return JodaBeanUtils.equal(getUid(), other.getUid()) &&
                    JodaBeanUtils.equal(getCharge(), other.getCharge()) &&
                    JodaBeanUtils.equal(getOrderId(), other.getOrderId()) &&
                    JodaBeanUtils.equal(getUnitId(), other.getUnitId()) &&
                    JodaBeanUtils.equal(getInvoiceId(), other.getInvoiceId()) &&
                    JodaBeanUtils.equal(getShippingId(), other.getShippingId()) &&
                    JodaBeanUtils.equal(getProcessedAt(), other.getProcessedAt()) &&
                    JodaBeanUtils.equal(getProductType(), other.getProductType());
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash += hash * 31 + JodaBeanUtils.hashCode(getUid());
        hash += hash * 31 + JodaBeanUtils.hashCode(getCharge());
        hash += hash * 31 + JodaBeanUtils.hashCode(getOrderId());
        hash += hash * 31 + JodaBeanUtils.hashCode(getUnitId());
        hash += hash * 31 + JodaBeanUtils.hashCode(getInvoiceId());
        hash += hash * 31 + JodaBeanUtils.hashCode(getShippingId());
        hash += hash * 31 + JodaBeanUtils.hashCode(getProcessedAt());
        hash += hash * 31 + JodaBeanUtils.hashCode(getProductType());
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(288);
        buf.append("Log{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    protected void toString(StringBuilder buf) {
        buf.append("uid").append('=').append(JodaBeanUtils.toString(getUid())).append(',').append(' ');
        buf.append("charge").append('=').append(JodaBeanUtils.toString(getCharge())).append(',').append(' ');
        buf.append("orderId").append('=').append(JodaBeanUtils.toString(getOrderId())).append(',').append(' ');
        buf.append("unitId").append('=').append(JodaBeanUtils.toString(getUnitId())).append(',').append(' ');
        buf.append("invoiceId").append('=').append(JodaBeanUtils.toString(getInvoiceId())).append(',').append(' ');
        buf.append("shippingId").append('=').append(JodaBeanUtils.toString(getShippingId())).append(',').append(' ');
        buf.append("processedAt").append('=').append(JodaBeanUtils.toString(getProcessedAt())).append(',').append(' ');
        buf.append("productType").append('=').append(JodaBeanUtils.toString(getProductType())).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code Log}.
     */
    public static class Meta extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code uid} property.
         */
        private final MetaProperty<String> uid = DirectMetaProperty.ofReadWrite(
                this, "uid", Log.class, String.class);
        /**
         * The meta-property for the {@code charge} property.
         */
        private final MetaProperty<String> charge = DirectMetaProperty.ofReadWrite(
                this, "charge", Log.class, String.class);
        /**
         * The meta-property for the {@code orderId} property.
         */
        private final MetaProperty<String> orderId = DirectMetaProperty.ofReadWrite(
                this, "orderId", Log.class, String.class);
        /**
         * The meta-property for the {@code unitId} property.
         */
        private final MetaProperty<String> unitId = DirectMetaProperty.ofReadWrite(
                this, "unitId", Log.class, String.class);
        /**
         * The meta-property for the {@code invoiceId} property.
         */
        private final MetaProperty<String> invoiceId = DirectMetaProperty.ofReadWrite(
                this, "invoiceId", Log.class, String.class);
        /**
         * The meta-property for the {@code shippingId} property.
         */
        private final MetaProperty<String> shippingId = DirectMetaProperty.ofReadWrite(
                this, "shippingId", Log.class, String.class);
        /**
         * The meta-property for the {@code processedAt} property.
         */
        private final MetaProperty<Date> processedAt = DirectMetaProperty.ofReadWrite(
                this, "processedAt", Log.class, Date.class);
        /**
         * The meta-property for the {@code productType} property.
         */
        private final MetaProperty<String> productType = DirectMetaProperty.ofReadWrite(
                this, "productType", Log.class, String.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null,
                "uid",
                "charge",
                "orderId",
                "unitId",
                "invoiceId",
                "shippingId",
                "processedAt",
                "productType");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case 115792:  // uid
                    return uid;
                case -1361632588:  // charge
                    return charge;
                case -1207110391:  // orderId
                    return orderId;
                case -840527425:  // unitId
                    return unitId;
                case -1739442904:  // invoiceId
                    return invoiceId;
                case 2113549161:  // shippingId
                    return shippingId;
                case 203012129:  // processedAt
                    return processedAt;
                case -1491615543:  // productType
                    return productType;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public BeanBuilder<? extends Log> builder() {
            return new DirectBeanBuilder<Log>(new Log());
        }

        @Override
        public Class<? extends Log> beanType() {
            return Log.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code uid} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> uid() {
            return uid;
        }

        /**
         * The meta-property for the {@code charge} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> charge() {
            return charge;
        }

        /**
         * The meta-property for the {@code orderId} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> orderId() {
            return orderId;
        }

        /**
         * The meta-property for the {@code unitId} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> unitId() {
            return unitId;
        }

        /**
         * The meta-property for the {@code invoiceId} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> invoiceId() {
            return invoiceId;
        }

        /**
         * The meta-property for the {@code shippingId} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> shippingId() {
            return shippingId;
        }

        /**
         * The meta-property for the {@code processedAt} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<Date> processedAt() {
            return processedAt;
        }

        /**
         * The meta-property for the {@code productType} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> productType() {
            return productType;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 115792:  // uid
                    return ((Log) bean).getUid();
                case -1361632588:  // charge
                    return ((Log) bean).getCharge();
                case -1207110391:  // orderId
                    return ((Log) bean).getOrderId();
                case -840527425:  // unitId
                    return ((Log) bean).getUnitId();
                case -1739442904:  // invoiceId
                    return ((Log) bean).getInvoiceId();
                case 2113549161:  // shippingId
                    return ((Log) bean).getShippingId();
                case 203012129:  // processedAt
                    return ((Log) bean).getProcessedAt();
                case -1491615543:  // productType
                    return ((Log) bean).getProductType();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 115792:  // uid
                    ((Log) bean).setUid((String) newValue);
                    return;
                case -1361632588:  // charge
                    ((Log) bean).setCharge((String) newValue);
                    return;
                case -1207110391:  // orderId
                    ((Log) bean).setOrderId((String) newValue);
                    return;
                case -840527425:  // unitId
                    ((Log) bean).setUnitId((String) newValue);
                    return;
                case -1739442904:  // invoiceId
                    ((Log) bean).setInvoiceId((String) newValue);
                    return;
                case 2113549161:  // shippingId
                    ((Log) bean).setShippingId((String) newValue);
                    return;
                case 203012129:  // processedAt
                    ((Log) bean).setProcessedAt((Date) newValue);
                    return;
                case -1491615543:  // productType
                    ((Log) bean).setProductType((String) newValue);
                    return;
            }
            super.propertySet(bean, propertyName, newValue, quiet);
        }

    }

    ///CLOVER:ON
    //-------------------------- AUTOGENERATED END --------------------------
}
