package com.m11n.hermes.core.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import org.joda.beans.*;
import org.joda.beans.impl.direct.*;

import javax.xml.bind.annotation.XmlRootElement;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.BeanDefinition;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectBean;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

@BeanDefinition
@JsonIgnoreProperties({"meta", "metaBean"})
@XmlRootElement(name = "print_request")
public class PrintRequest extends DirectBean
{
    @PropertyDefinition
    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    private String type;

    @PropertyDefinition
    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    private List<String> orderIds;

    @PropertyDefinition
    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    private String templates;

    @PropertyDefinition
    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    private Integer chargeSize;

    public PrintRequest() {

    }

    public PrintRequest(String type, List<String> orderIds, Integer chargeSize) {
        this.type = type;
        this.orderIds = orderIds;
        this.chargeSize = chargeSize;

    }

    public PrintRequest(String type, String orderId, Integer chargeSize) {
        this(type, Collections.singletonList(orderId), chargeSize);
    }

    //------------------------- AUTOGENERATED START -------------------------
    ///CLOVER:OFF
    /**
     * The meta-bean for {@code PrintRequest}.
     * @return the meta-bean, not null
     */
    public static PrintRequest.Meta meta() {
        return PrintRequest.Meta.INSTANCE;
    }

    static {
        JodaBeanUtils.registerMetaBean(PrintRequest.Meta.INSTANCE);
    }

    @Override
    public PrintRequest.Meta metaBean() {
        return PrintRequest.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the type.
     * @return the value of the property
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the type.
     * @param type  the new value of the property
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Gets the the {@code type} property.
     * @return the property, not null
     */
    public final Property<String> type() {
        return metaBean().type().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the orderIds.
     * @return the value of the property
     */
    public List<String> getOrderIds() {
        return orderIds;
    }

    /**
     * Sets the orderIds.
     * @param orderIds  the new value of the property
     */
    public void setOrderIds(List<String> orderIds) {
        this.orderIds = orderIds;
    }

    /**
     * Gets the the {@code orderIds} property.
     * @return the property, not null
     */
    public final Property<List<String>> orderIds() {
        return metaBean().orderIds().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the templates.
     * @return the value of the property
     */
    public String getTemplates() {
        return templates;
    }

    /**
     * Sets the templates.
     * @param templates  the new value of the property
     */
    public void setTemplates(String templates) {
        this.templates = templates;
    }

    /**
     * Gets the the {@code templates} property.
     * @return the property, not null
     */
    public final Property<String> templates() {
        return metaBean().templates().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the chargeSize.
     * @return the value of the property
     */
    public Integer getChargeSize() {
        return chargeSize;
    }

    /**
     * Sets the chargeSize.
     * @param chargeSize  the new value of the property
     */
    public void setChargeSize(Integer chargeSize) {
        this.chargeSize = chargeSize;
    }

    /**
     * Gets the the {@code chargeSize} property.
     * @return the property, not null
     */
    public final Property<Integer> chargeSize() {
        return metaBean().chargeSize().createProperty(this);
    }

    //-----------------------------------------------------------------------
    @Override
    public PrintRequest clone() {
        return JodaBeanUtils.cloneAlways(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            PrintRequest other = (PrintRequest) obj;
            return JodaBeanUtils.equal(getType(), other.getType()) &&
                    JodaBeanUtils.equal(getOrderIds(), other.getOrderIds()) &&
                    JodaBeanUtils.equal(getTemplates(), other.getTemplates()) &&
                    JodaBeanUtils.equal(getChargeSize(), other.getChargeSize());
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash += hash * 31 + JodaBeanUtils.hashCode(getType());
        hash += hash * 31 + JodaBeanUtils.hashCode(getOrderIds());
        hash += hash * 31 + JodaBeanUtils.hashCode(getTemplates());
        hash += hash * 31 + JodaBeanUtils.hashCode(getChargeSize());
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(160);
        buf.append("PrintRequest{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    protected void toString(StringBuilder buf) {
        buf.append("type").append('=').append(JodaBeanUtils.toString(getType())).append(',').append(' ');
        buf.append("orderIds").append('=').append(JodaBeanUtils.toString(getOrderIds())).append(',').append(' ');
        buf.append("templates").append('=').append(JodaBeanUtils.toString(getTemplates())).append(',').append(' ');
        buf.append("chargeSize").append('=').append(JodaBeanUtils.toString(getChargeSize())).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code PrintRequest}.
     */
    public static class Meta extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code type} property.
         */
        private final MetaProperty<String> type = DirectMetaProperty.ofReadWrite(
                this, "type", PrintRequest.class, String.class);
        /**
         * The meta-property for the {@code orderIds} property.
         */
        @SuppressWarnings({"unchecked", "rawtypes" })
        private final MetaProperty<List<String>> orderIds = DirectMetaProperty.ofReadWrite(
                this, "orderIds", PrintRequest.class, (Class) List.class);
        /**
         * The meta-property for the {@code templates} property.
         */
        private final MetaProperty<String> templates = DirectMetaProperty.ofReadWrite(
                this, "templates", PrintRequest.class, String.class);
        /**
         * The meta-property for the {@code chargeSize} property.
         */
        private final MetaProperty<Integer> chargeSize = DirectMetaProperty.ofReadWrite(
                this, "chargeSize", PrintRequest.class, Integer.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null,
                "type",
                "orderIds",
                "templates",
                "chargeSize");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case 3575610:  // type
                    return type;
                case 1234283658:  // orderIds
                    return orderIds;
                case 1981727545:  // templates
                    return templates;
                case 1418067157:  // chargeSize
                    return chargeSize;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public BeanBuilder<? extends PrintRequest> builder() {
            return new DirectBeanBuilder<PrintRequest>(new PrintRequest());
        }

        @Override
        public Class<? extends PrintRequest> beanType() {
            return PrintRequest.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code type} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> type() {
            return type;
        }

        /**
         * The meta-property for the {@code orderIds} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<List<String>> orderIds() {
            return orderIds;
        }

        /**
         * The meta-property for the {@code templates} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> templates() {
            return templates;
        }

        /**
         * The meta-property for the {@code chargeSize} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<Integer> chargeSize() {
            return chargeSize;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 3575610:  // type
                    return ((PrintRequest) bean).getType();
                case 1234283658:  // orderIds
                    return ((PrintRequest) bean).getOrderIds();
                case 1981727545:  // templates
                    return ((PrintRequest) bean).getTemplates();
                case 1418067157:  // chargeSize
                    return ((PrintRequest) bean).getChargeSize();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @SuppressWarnings("unchecked")
        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 3575610:  // type
                    ((PrintRequest) bean).setType((String) newValue);
                    return;
                case 1234283658:  // orderIds
                    ((PrintRequest) bean).setOrderIds((List<String>) newValue);
                    return;
                case 1981727545:  // templates
                    ((PrintRequest) bean).setTemplates((String) newValue);
                    return;
                case 1418067157:  // chargeSize
                    ((PrintRequest) bean).setChargeSize((Integer) newValue);
                    return;
            }
            super.propertySet(bean, propertyName, newValue, quiet);
        }

    }

    ///CLOVER:ON
    //-------------------------- AUTOGENERATED END --------------------------
}
