package com.m11n.hermes.core.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import org.hibernate.annotations.GenericGenerator;
import org.springframework.data.annotation.Id;

import javax.persistence.*;
import javax.xml.bind.annotation.XmlRootElement;
import java.util.Date;
import java.util.Map;
import org.joda.beans.Bean;
import org.joda.beans.BeanBuilder;
import org.joda.beans.BeanDefinition;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectBean;
import org.joda.beans.impl.direct.DirectBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

@BeanDefinition
@JsonIgnoreProperties({"meta", "metaBean"})
@XmlRootElement(name = "printer_log")
@Entity
@Table(name = "printer_log")
public class PrinterLog extends DirectBean
{
    @PropertyDefinition
    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @Id
    @javax.persistence.Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    @Column(name = "uuid", unique = true)
    private String uid;

    @PropertyDefinition
    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @Column(name = "charge")
    private String charge;

    @PropertyDefinition
    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @Column(name = "order_id", unique = true)
    private String orderId;

    @PropertyDefinition
    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @Column(name = "unit_id")
    private String unitId;

    @PropertyDefinition
    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @Column(name = "invoice_id")
    private String invoiceId;

    @PropertyDefinition
    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @Column(name = "shipping_id")
    private String shippingId;

    @PropertyDefinition
    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @Column(name = "processed_at")
    private Date processedAt;

    @PropertyDefinition
    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @Column(name = "printed_at")
    private Date printedAt;

    @PropertyDefinition
    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @Column(name = "product_type")
    private String productType;

    @PropertyDefinition
    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @Column(name = "status")
    private String status;

    @PropertyDefinition
    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @Column(name = "invoice")
    private Boolean invoice;

    @PropertyDefinition
    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @Column(name = "label")
    private Boolean label;

    @PropertyDefinition
    @JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
    @Column(name = "selected")
    private Boolean selected;

    //------------------------- AUTOGENERATED START -------------------------
    ///CLOVER:OFF
    /**
     * The meta-bean for {@code PrinterLog}.
     * @return the meta-bean, not null
     */
    public static PrinterLog.Meta meta() {
        return PrinterLog.Meta.INSTANCE;
    }

    static {
        JodaBeanUtils.registerMetaBean(PrinterLog.Meta.INSTANCE);
    }

    @Override
    public PrinterLog.Meta metaBean() {
        return PrinterLog.Meta.INSTANCE;
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the uid.
     * @return the value of the property
     */
    public String getUid() {
        return uid;
    }

    /**
     * Sets the uid.
     * @param uid  the new value of the property
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * Gets the the {@code uid} property.
     * @return the property, not null
     */
    public final Property<String> uid() {
        return metaBean().uid().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the charge.
     * @return the value of the property
     */
    public String getCharge() {
        return charge;
    }

    /**
     * Sets the charge.
     * @param charge  the new value of the property
     */
    public void setCharge(String charge) {
        this.charge = charge;
    }

    /**
     * Gets the the {@code charge} property.
     * @return the property, not null
     */
    public final Property<String> charge() {
        return metaBean().charge().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the orderId.
     * @return the value of the property
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * Sets the orderId.
     * @param orderId  the new value of the property
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * Gets the the {@code orderId} property.
     * @return the property, not null
     */
    public final Property<String> orderId() {
        return metaBean().orderId().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the unitId.
     * @return the value of the property
     */
    public String getUnitId() {
        return unitId;
    }

    /**
     * Sets the unitId.
     * @param unitId  the new value of the property
     */
    public void setUnitId(String unitId) {
        this.unitId = unitId;
    }

    /**
     * Gets the the {@code unitId} property.
     * @return the property, not null
     */
    public final Property<String> unitId() {
        return metaBean().unitId().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the invoiceId.
     * @return the value of the property
     */
    public String getInvoiceId() {
        return invoiceId;
    }

    /**
     * Sets the invoiceId.
     * @param invoiceId  the new value of the property
     */
    public void setInvoiceId(String invoiceId) {
        this.invoiceId = invoiceId;
    }

    /**
     * Gets the the {@code invoiceId} property.
     * @return the property, not null
     */
    public final Property<String> invoiceId() {
        return metaBean().invoiceId().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the shippingId.
     * @return the value of the property
     */
    public String getShippingId() {
        return shippingId;
    }

    /**
     * Sets the shippingId.
     * @param shippingId  the new value of the property
     */
    public void setShippingId(String shippingId) {
        this.shippingId = shippingId;
    }

    /**
     * Gets the the {@code shippingId} property.
     * @return the property, not null
     */
    public final Property<String> shippingId() {
        return metaBean().shippingId().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the processedAt.
     * @return the value of the property
     */
    public Date getProcessedAt() {
        return processedAt;
    }

    /**
     * Sets the processedAt.
     * @param processedAt  the new value of the property
     */
    public void setProcessedAt(Date processedAt) {
        this.processedAt = processedAt;
    }

    /**
     * Gets the the {@code processedAt} property.
     * @return the property, not null
     */
    public final Property<Date> processedAt() {
        return metaBean().processedAt().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the printedAt.
     * @return the value of the property
     */
    public Date getPrintedAt() {
        return printedAt;
    }

    /**
     * Sets the printedAt.
     * @param printedAt  the new value of the property
     */
    public void setPrintedAt(Date printedAt) {
        this.printedAt = printedAt;
    }

    /**
     * Gets the the {@code printedAt} property.
     * @return the property, not null
     */
    public final Property<Date> printedAt() {
        return metaBean().printedAt().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the productType.
     * @return the value of the property
     */
    public String getProductType() {
        return productType;
    }

    /**
     * Sets the productType.
     * @param productType  the new value of the property
     */
    public void setProductType(String productType) {
        this.productType = productType;
    }

    /**
     * Gets the the {@code productType} property.
     * @return the property, not null
     */
    public final Property<String> productType() {
        return metaBean().productType().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the status.
     * @return the value of the property
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the status.
     * @param status  the new value of the property
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Gets the the {@code status} property.
     * @return the property, not null
     */
    public final Property<String> status() {
        return metaBean().status().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the invoice.
     * @return the value of the property
     */
    public Boolean getInvoice() {
        return invoice;
    }

    /**
     * Sets the invoice.
     * @param invoice  the new value of the property
     */
    public void setInvoice(Boolean invoice) {
        this.invoice = invoice;
    }

    /**
     * Gets the the {@code invoice} property.
     * @return the property, not null
     */
    public final Property<Boolean> invoice() {
        return metaBean().invoice().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the label.
     * @return the value of the property
     */
    public Boolean getLabel() {
        return label;
    }

    /**
     * Sets the label.
     * @param label  the new value of the property
     */
    public void setLabel(Boolean label) {
        this.label = label;
    }

    /**
     * Gets the the {@code label} property.
     * @return the property, not null
     */
    public final Property<Boolean> label() {
        return metaBean().label().createProperty(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Gets the selected.
     * @return the value of the property
     */
    public Boolean getSelected() {
        return selected;
    }

    /**
     * Sets the selected.
     * @param selected  the new value of the property
     */
    public void setSelected(Boolean selected) {
        this.selected = selected;
    }

    /**
     * Gets the the {@code selected} property.
     * @return the property, not null
     */
    public final Property<Boolean> selected() {
        return metaBean().selected().createProperty(this);
    }

    //-----------------------------------------------------------------------
    @Override
    public PrinterLog clone() {
        return JodaBeanUtils.cloneAlways(this);
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        if (obj != null && obj.getClass() == this.getClass()) {
            PrinterLog other = (PrinterLog) obj;
            return JodaBeanUtils.equal(getUid(), other.getUid()) &&
                    JodaBeanUtils.equal(getCharge(), other.getCharge()) &&
                    JodaBeanUtils.equal(getOrderId(), other.getOrderId()) &&
                    JodaBeanUtils.equal(getUnitId(), other.getUnitId()) &&
                    JodaBeanUtils.equal(getInvoiceId(), other.getInvoiceId()) &&
                    JodaBeanUtils.equal(getShippingId(), other.getShippingId()) &&
                    JodaBeanUtils.equal(getProcessedAt(), other.getProcessedAt()) &&
                    JodaBeanUtils.equal(getPrintedAt(), other.getPrintedAt()) &&
                    JodaBeanUtils.equal(getProductType(), other.getProductType()) &&
                    JodaBeanUtils.equal(getStatus(), other.getStatus()) &&
                    JodaBeanUtils.equal(getInvoice(), other.getInvoice()) &&
                    JodaBeanUtils.equal(getLabel(), other.getLabel()) &&
                    JodaBeanUtils.equal(getSelected(), other.getSelected());
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = getClass().hashCode();
        hash += hash * 31 + JodaBeanUtils.hashCode(getUid());
        hash += hash * 31 + JodaBeanUtils.hashCode(getCharge());
        hash += hash * 31 + JodaBeanUtils.hashCode(getOrderId());
        hash += hash * 31 + JodaBeanUtils.hashCode(getUnitId());
        hash += hash * 31 + JodaBeanUtils.hashCode(getInvoiceId());
        hash += hash * 31 + JodaBeanUtils.hashCode(getShippingId());
        hash += hash * 31 + JodaBeanUtils.hashCode(getProcessedAt());
        hash += hash * 31 + JodaBeanUtils.hashCode(getPrintedAt());
        hash += hash * 31 + JodaBeanUtils.hashCode(getProductType());
        hash += hash * 31 + JodaBeanUtils.hashCode(getStatus());
        hash += hash * 31 + JodaBeanUtils.hashCode(getInvoice());
        hash += hash * 31 + JodaBeanUtils.hashCode(getLabel());
        hash += hash * 31 + JodaBeanUtils.hashCode(getSelected());
        return hash;
    }

    @Override
    public String toString() {
        StringBuilder buf = new StringBuilder(448);
        buf.append("PrinterLog{");
        int len = buf.length();
        toString(buf);
        if (buf.length() > len) {
            buf.setLength(buf.length() - 2);
        }
        buf.append('}');
        return buf.toString();
    }

    protected void toString(StringBuilder buf) {
        buf.append("uid").append('=').append(JodaBeanUtils.toString(getUid())).append(',').append(' ');
        buf.append("charge").append('=').append(JodaBeanUtils.toString(getCharge())).append(',').append(' ');
        buf.append("orderId").append('=').append(JodaBeanUtils.toString(getOrderId())).append(',').append(' ');
        buf.append("unitId").append('=').append(JodaBeanUtils.toString(getUnitId())).append(',').append(' ');
        buf.append("invoiceId").append('=').append(JodaBeanUtils.toString(getInvoiceId())).append(',').append(' ');
        buf.append("shippingId").append('=').append(JodaBeanUtils.toString(getShippingId())).append(',').append(' ');
        buf.append("processedAt").append('=').append(JodaBeanUtils.toString(getProcessedAt())).append(',').append(' ');
        buf.append("printedAt").append('=').append(JodaBeanUtils.toString(getPrintedAt())).append(',').append(' ');
        buf.append("productType").append('=').append(JodaBeanUtils.toString(getProductType())).append(',').append(' ');
        buf.append("status").append('=').append(JodaBeanUtils.toString(getStatus())).append(',').append(' ');
        buf.append("invoice").append('=').append(JodaBeanUtils.toString(getInvoice())).append(',').append(' ');
        buf.append("label").append('=').append(JodaBeanUtils.toString(getLabel())).append(',').append(' ');
        buf.append("selected").append('=').append(JodaBeanUtils.toString(getSelected())).append(',').append(' ');
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-bean for {@code PrinterLog}.
     */
    public static class Meta extends DirectMetaBean {
        /**
         * The singleton instance of the meta-bean.
         */
        static final Meta INSTANCE = new Meta();

        /**
         * The meta-property for the {@code uid} property.
         */
        private final MetaProperty<String> uid = DirectMetaProperty.ofReadWrite(
                this, "uid", PrinterLog.class, String.class);
        /**
         * The meta-property for the {@code charge} property.
         */
        private final MetaProperty<String> charge = DirectMetaProperty.ofReadWrite(
                this, "charge", PrinterLog.class, String.class);
        /**
         * The meta-property for the {@code orderId} property.
         */
        private final MetaProperty<String> orderId = DirectMetaProperty.ofReadWrite(
                this, "orderId", PrinterLog.class, String.class);
        /**
         * The meta-property for the {@code unitId} property.
         */
        private final MetaProperty<String> unitId = DirectMetaProperty.ofReadWrite(
                this, "unitId", PrinterLog.class, String.class);
        /**
         * The meta-property for the {@code invoiceId} property.
         */
        private final MetaProperty<String> invoiceId = DirectMetaProperty.ofReadWrite(
                this, "invoiceId", PrinterLog.class, String.class);
        /**
         * The meta-property for the {@code shippingId} property.
         */
        private final MetaProperty<String> shippingId = DirectMetaProperty.ofReadWrite(
                this, "shippingId", PrinterLog.class, String.class);
        /**
         * The meta-property for the {@code processedAt} property.
         */
        private final MetaProperty<Date> processedAt = DirectMetaProperty.ofReadWrite(
                this, "processedAt", PrinterLog.class, Date.class);
        /**
         * The meta-property for the {@code printedAt} property.
         */
        private final MetaProperty<Date> printedAt = DirectMetaProperty.ofReadWrite(
                this, "printedAt", PrinterLog.class, Date.class);
        /**
         * The meta-property for the {@code productType} property.
         */
        private final MetaProperty<String> productType = DirectMetaProperty.ofReadWrite(
                this, "productType", PrinterLog.class, String.class);
        /**
         * The meta-property for the {@code status} property.
         */
        private final MetaProperty<String> status = DirectMetaProperty.ofReadWrite(
                this, "status", PrinterLog.class, String.class);
        /**
         * The meta-property for the {@code invoice} property.
         */
        private final MetaProperty<Boolean> invoice = DirectMetaProperty.ofReadWrite(
                this, "invoice", PrinterLog.class, Boolean.class);
        /**
         * The meta-property for the {@code label} property.
         */
        private final MetaProperty<Boolean> label = DirectMetaProperty.ofReadWrite(
                this, "label", PrinterLog.class, Boolean.class);
        /**
         * The meta-property for the {@code selected} property.
         */
        private final MetaProperty<Boolean> selected = DirectMetaProperty.ofReadWrite(
                this, "selected", PrinterLog.class, Boolean.class);
        /**
         * The meta-properties.
         */
        private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
                this, null,
                "uid",
                "charge",
                "orderId",
                "unitId",
                "invoiceId",
                "shippingId",
                "processedAt",
                "printedAt",
                "productType",
                "status",
                "invoice",
                "label",
                "selected");

        /**
         * Restricted constructor.
         */
        protected Meta() {
        }

        @Override
        protected MetaProperty<?> metaPropertyGet(String propertyName) {
            switch (propertyName.hashCode()) {
                case 115792:  // uid
                    return uid;
                case -1361632588:  // charge
                    return charge;
                case -1207110391:  // orderId
                    return orderId;
                case -840527425:  // unitId
                    return unitId;
                case -1739442904:  // invoiceId
                    return invoiceId;
                case 2113549161:  // shippingId
                    return shippingId;
                case 203012129:  // processedAt
                    return processedAt;
                case -1796473505:  // printedAt
                    return printedAt;
                case -1491615543:  // productType
                    return productType;
                case -892481550:  // status
                    return status;
                case 1960198957:  // invoice
                    return invoice;
                case 102727412:  // label
                    return label;
                case 1191572123:  // selected
                    return selected;
            }
            return super.metaPropertyGet(propertyName);
        }

        @Override
        public BeanBuilder<? extends PrinterLog> builder() {
            return new DirectBeanBuilder<PrinterLog>(new PrinterLog());
        }

        @Override
        public Class<? extends PrinterLog> beanType() {
            return PrinterLog.class;
        }

        @Override
        public Map<String, MetaProperty<?>> metaPropertyMap() {
            return metaPropertyMap$;
        }

        //-----------------------------------------------------------------------
        /**
         * The meta-property for the {@code uid} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> uid() {
            return uid;
        }

        /**
         * The meta-property for the {@code charge} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> charge() {
            return charge;
        }

        /**
         * The meta-property for the {@code orderId} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> orderId() {
            return orderId;
        }

        /**
         * The meta-property for the {@code unitId} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> unitId() {
            return unitId;
        }

        /**
         * The meta-property for the {@code invoiceId} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> invoiceId() {
            return invoiceId;
        }

        /**
         * The meta-property for the {@code shippingId} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> shippingId() {
            return shippingId;
        }

        /**
         * The meta-property for the {@code processedAt} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<Date> processedAt() {
            return processedAt;
        }

        /**
         * The meta-property for the {@code printedAt} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<Date> printedAt() {
            return printedAt;
        }

        /**
         * The meta-property for the {@code productType} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> productType() {
            return productType;
        }

        /**
         * The meta-property for the {@code status} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<String> status() {
            return status;
        }

        /**
         * The meta-property for the {@code invoice} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<Boolean> invoice() {
            return invoice;
        }

        /**
         * The meta-property for the {@code label} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<Boolean> label() {
            return label;
        }

        /**
         * The meta-property for the {@code selected} property.
         * @return the meta-property, not null
         */
        public final MetaProperty<Boolean> selected() {
            return selected;
        }

        //-----------------------------------------------------------------------
        @Override
        protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 115792:  // uid
                    return ((PrinterLog) bean).getUid();
                case -1361632588:  // charge
                    return ((PrinterLog) bean).getCharge();
                case -1207110391:  // orderId
                    return ((PrinterLog) bean).getOrderId();
                case -840527425:  // unitId
                    return ((PrinterLog) bean).getUnitId();
                case -1739442904:  // invoiceId
                    return ((PrinterLog) bean).getInvoiceId();
                case 2113549161:  // shippingId
                    return ((PrinterLog) bean).getShippingId();
                case 203012129:  // processedAt
                    return ((PrinterLog) bean).getProcessedAt();
                case -1796473505:  // printedAt
                    return ((PrinterLog) bean).getPrintedAt();
                case -1491615543:  // productType
                    return ((PrinterLog) bean).getProductType();
                case -892481550:  // status
                    return ((PrinterLog) bean).getStatus();
                case 1960198957:  // invoice
                    return ((PrinterLog) bean).getInvoice();
                case 102727412:  // label
                    return ((PrinterLog) bean).getLabel();
                case 1191572123:  // selected
                    return ((PrinterLog) bean).getSelected();
            }
            return super.propertyGet(bean, propertyName, quiet);
        }

        @Override
        protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
            switch (propertyName.hashCode()) {
                case 115792:  // uid
                    ((PrinterLog) bean).setUid((String) newValue);
                    return;
                case -1361632588:  // charge
                    ((PrinterLog) bean).setCharge((String) newValue);
                    return;
                case -1207110391:  // orderId
                    ((PrinterLog) bean).setOrderId((String) newValue);
                    return;
                case -840527425:  // unitId
                    ((PrinterLog) bean).setUnitId((String) newValue);
                    return;
                case -1739442904:  // invoiceId
                    ((PrinterLog) bean).setInvoiceId((String) newValue);
                    return;
                case 2113549161:  // shippingId
                    ((PrinterLog) bean).setShippingId((String) newValue);
                    return;
                case 203012129:  // processedAt
                    ((PrinterLog) bean).setProcessedAt((Date) newValue);
                    return;
                case -1796473505:  // printedAt
                    ((PrinterLog) bean).setPrintedAt((Date) newValue);
                    return;
                case -1491615543:  // productType
                    ((PrinterLog) bean).setProductType((String) newValue);
                    return;
                case -892481550:  // status
                    ((PrinterLog) bean).setStatus((String) newValue);
                    return;
                case 1960198957:  // invoice
                    ((PrinterLog) bean).setInvoice((Boolean) newValue);
                    return;
                case 102727412:  // label
                    ((PrinterLog) bean).setLabel((Boolean) newValue);
                    return;
                case 1191572123:  // selected
                    ((PrinterLog) bean).setSelected((Boolean) newValue);
                    return;
            }
            super.propertySet(bean, propertyName, newValue, quiet);
        }

    }

    ///CLOVER:ON
    //-------------------------- AUTOGENERATED END --------------------------
}
