DROP TABLE paypal_raw;
CREATE TABLE `paypal_raw` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `code1` varchar(10) NOT NULL,
  `Transaktionscode` varchar(200) NOT NULL,
  `Rechnungsnummer` varchar(200) NOT NULL,
  `PayPal-Referenznummer` varchar(200) NOT NULL,
  `PayPal-Referenznummer_Typ` varchar(200) NOT NULL,
  `Transaktionsereigniscode` varchar(200) NOT NULL,
  `Transaktionseinleitungsdatum` varchar(200) NOT NULL,
  `Transaktionsabschlussdatum` varchar(200) NOT NULL,
  `Transaktion_Gutschrift_oder_Belastung` varchar(200) NOT NULL,
  `Bruttotransaktionsbetrag` varchar(200) NOT NULL,
  `Währung_der_Transaktion` varchar(200) NOT NULL,
  `Gebühr_Soll_oder_Haben` varchar(200) NOT NULL,
  `Gebührenbetrag` varchar(200) NOT NULL,
  `Währung_der_Gebühr` varchar(200) NOT NULL,
  `Transaktionsstatus` varchar(200) NOT NULL,
  `Versicherungsbetrag` varchar(200) NOT NULL,
  `Umsatzsteuerbetrag` varchar(200) NOT NULL,
  `Versandkosten` varchar(200) NOT NULL,
  `Transaktionsgegenstand` varchar(200) NOT NULL,
  `Transaktionshinweis` varchar(200) NOT NULL,
  `Kontokennung_des_Käufers` varchar(200) NOT NULL,
  `Adressenstatus_des_Käufers` varchar(200) NOT NULL,
  `Artikelbezeichnung` varchar(200) NOT NULL,
  `Artikelnummer` varchar(200) NOT NULL,
  `Name_Option_1` varchar(200) NOT NULL,
  `Wert_Option_1` varchar(200) NOT NULL,
  `Name_Option_2` varchar(200) NOT NULL,
  `Wert_Option_2` varchar(200) NOT NULL,
  `Auktions-Site` varchar(200) NOT NULL,
  `Käufer-ID` varchar(200) NOT NULL,
  `Auktionsende` varchar(200) NOT NULL,
  `Versandadresse_Zeile_1` varchar(200) NOT NULL,
  `Lieferadresse_Zeile_2` varchar(200) NOT NULL,
  `Versandadresse_Ort` varchar(200) NOT NULL,
  `Lieferadresse_Bundesland` varchar(200) NOT NULL,
  `Lieferadresse_PLZ` varchar(200) NOT NULL,
  `Versandadresse_Land` varchar(200) NOT NULL,
  `Versandmethode` varchar(200) NOT NULL,
  `Benutzerdefiniertes_Feld` varchar(200) NOT NULL,
  `Rechnungsadresse_Zeile_1` varchar(200) NOT NULL,
  `Rechnungsadresse_Zeile_2` varchar(200) NOT NULL,
  `Rechnungsadresse_Ort` varchar(200) NOT NULL,
  `Rechnungsadresse_Staat` varchar(200) NOT NULL,
  `Rechnungsadresse_PLZ` varchar(200) NOT NULL,
  `Rechnungsadresse_Land` varchar(200) NOT NULL,
  `Kundennummer` varchar(200) NOT NULL,
  `Vorname` varchar(200) NOT NULL,
  `Nachname` varchar(200) NOT NULL,
  `Firmenname` varchar(200) NOT NULL,
  `Kartentyp` varchar(200) NOT NULL,
  `Zahlungsquelle` varchar(200) NOT NULL,
  `Versandname` varchar(200) NOT NULL,
  `Autorisierungsstatus` varchar(200) NOT NULL,
  `Anspruch_auf_Verkäuferschutz` varchar(200) NOT NULL,
  `Zahlungsverfolgungs-ID` varchar(200) NOT NULL,
  `Filiale` varchar(200) NOT NULL,
  `Kasse` varchar(200) NOT NULL,
  `Gutscheine` varchar(200) NOT NULL,
  `Sonderangebote` varchar(200) NOT NULL,
  `Kundenkartennummer` varchar(200) NOT NULL,
  `Zahlungstyp` varchar(200) NOT NULL,
  `Alternative_Lieferadresse_Zeile_1` varchar(200) NOT NULL,
  `Alternative_Lieferadresse_Zeile_2` varchar(200) NOT NULL,
  `Alternative_Lieferadresse_Ort` varchar(200) NOT NULL,
  `Alternative_Lieferadresse_Bundesland` varchar(200) NOT NULL,
  `Alternative_Lieferadresse_Land` varchar(200) NOT NULL,
  `Alternative_Lieferadresse_PLZ` varchar(200) NOT NULL,
  `3PL-Referenznummer` varchar(200) NOT NULL,
  `Geschenkkartennummer` varchar(200) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE fidor_raw;
CREATE TABLE `fidor_raw` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `date` varchar(20) NOT NULL,
  `text` text NOT NULL,
  `text2` text NOT NULL,
  `value` varchar(25) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE hypovereinsbank_raw;
CREATE TABLE `hypovereinsbank_raw` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `Kontonummer` varchar(50) NOT NULL,
  `Buchungsdatum` varchar(50) NOT NULL,
  `Valuta` varchar(50) NOT NULL,
  `Empfaenger_1` varchar(50) NOT NULL,
  `Empfaenger_2` varchar(50) NOT NULL,
  `Verwendungszweck` text NOT NULL,
  `Betrag` varchar(20) NOT NULL,
  `Waehrung` varchar(30) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;